disabled = false
locale = "zh-cn"
label = "简体中文"
weight = 1
title = "Tequila's 学习笔记"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "学习记录与知识分享"

[params.author]
  name = "Tequila"
  image = "img/avr.png"
  headline = "计算机的世界里没有黑魔法"
  bio = "The world is the idea that comprehends itself."
  links = [
    { github = "https://github.com/latnx" },
  ]
