languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Tequila's Blog"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "学习记录与知识分享，params.description"

[params.author]
  name = "Tequila"
  image = "img/avr.png"
  headline = "计算机的世界里没有黑魔法"
  bio = "The world is the idea that comprehends itself."
  links = [
    { github = "https://github.com/latnx" },
  ]