# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "笔记"
  pageRef = "docs/notes"
  weight = 5

[[main]]
  name = "理论"
  pageRef = "docs/theory"
  weight = 10

[[main]]
  name = "技术"
  pageRef = "technology"
  weight = 20

[[main]]
  name = "论文"
  pageRef = "docs/paper"
  weight = 30

[[main]]
  name = "其他"
  weight = 100

[[main]]
  name = "哲学"
  parent = "其他"
  pageRef = "docs/philosophy"
  weight = 16

[[main]]
  name = "金融"
  parent = "其他"
  pageRef = "finance"
  weight = 30

[[main]]
  name = "音乐"
  parent = "其他"
  pageRef = "docs/music"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Latnx"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "作者"
   pageRef = "authors"
   weight = 20
